const state = {};

var data = [
    {
        "id": "1",
        "Rua": "ALFREDO ROGADO (AR)",
        "Bairro": "Conj. Habitacional Eugênio Motta",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "5",
        "CEP": "18542-458",
    },
    {
        "id": "2",
        "Rua": "ALAN KARDEC (AK)",
        "Bairro": "Convívio do Santo",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "6",
        "CEP": "18542-434",
    },
    {
        "id": "3",
        "Rua": "ANGELO FUSTAINO (AF)",
        "Bairro": "Conj. Habitacional Benedito José Diana",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "1 - FRANCIELLE",
        "CEP": "18542-380",
    },
    {
        "id": "4",
        "Rua": "APARICIO PIRES (AP)",
        "Bairro": "Conj. Habitacional Eugênio Motta",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "5",
        "CEP": "18542-456",
    },
    {
        "id": "5",
        "Rua": "AURELIA VERONEZE GUTIERREZ (AVG)",
        "Bairro": "Conj. Habitacional Benedito José Diana",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "3 - ANDREIA",
        "CEP": "18542-388",
    },
    {
        "id": "6",
        "Rua": "BENEDITO APARECIDO MANFRINATI (BAM)",
        "Bairro": "Conj. Habitacional Benedito José Diana",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "3 - ANDREIA",
        "CEP": "18542-390",
    },
    {
        "id": "7",
        "Rua": "BOM JESUS (BJ)",
        "Bairro": "Convívio do Santo",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "6",
        "CEP": "18542-438",
    },
    {
        "id": "8",
        "Rua": "BOM PASTOR (BP)",
        "Bairro": "Convívio do Santo",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "6",
        "CEP": "18542-432",
    },
    {
        "id": "9",
        "Rua": "DANIEL DE CAMARGO TABORDA (DCT) - (5-484)",
        "Bairro": "Conjunto Habitacional Eugênio Motta (até 175)",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "4 - GUILHERME",
        "CEP": "18542-460",
    },
    {
        "id": "10",
        "Rua": "HANS REDER (HR)",
        "Bairro": "Conj. Habitacional Eugênio Motta",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "5",
        "CEP": "18542-454",
    },
    {
        "id": "11",
        "Rua": "JOAO DIANA SOBRINHO (JDS) - 348 em diante",
        "Bairro": "Jardim Excelsior",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "1 - FRANCIELLE",
        "CEP": "18542-324",
    },
    {
        "id": "12",
        "Rua": "MAESTRO MANOEL JOSE DE CACALAZANS (MMJC)",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "4 - GUILHERME",
        "CEP": "18542-374",
    },
    {
        "id": "13",
        "Rua": "MAHATMA GANDHI (MG)",
        "Bairro": "Convívio do Santo",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "6",
        "CEP": "18542-430",
    },
    {
        "id": "14",
        "Rua": "MARCO AURELIO BATISTELA (MAB)",
        "Bairro": "Parque Residencial Água Branca",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "5",
        "CEP": "18542-472",
    },
    {
        "id": "15",
        "Rua": "MARIA EUGENIA PIMENTA DIANA (MEPD) - 137-303",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "2",
        "CEP": "18542-360",
    },
    {
        "id": "16",
        "Rua": "MARIO PIRES DE ALMEIDA (MPA)",
        "Bairro": "Jardim Excelsior",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "1 - FRANCIELLE",
        "CEP": "18542-320",
    },
    {
        "id": "17",
        "Rua": "OLIVIO TOME (OT)",
        "Bairro": "Jardim Excelsior",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "2",
        "CEP": "18542-326",
    },
    {
        "id": "18",
        "Rua": "OSVALDO NOVAES DE CARVALHO (ONC) - 125-309",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "4 - GUILHERME",
        "CEP": "18542-366",
    },
    {
        "id": "19",
        "Rua": "OTONIEL RODRIGUES (OR)",
        "Bairro": "Parque Residencial Água Branca",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "5",
        "CEP": "18542-474",
    },
    {
        "id": "20",
        "Rua": "PADRE JOSE DE ANCHIETA (PJA)",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "4 - GUILHERME",
        "CEP": "18542-370",
    },
    {
        "id": "21",
        "Rua": "PLINIO MARTINS SIQUEIRA (PMS)",
        "Bairro": "Conj. Habitacional Benedito José Diana",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "3 - ANDREIA",
        "CEP": "18542-384",
    },
    {
        "id": "22",
        "Rua": "REI DAVI (RD)",
        "Bairro": "Convívio do Santo",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "6",
        "CEP": "18542-436",
    },
    {
        "id": "23",
        "Rua": "SILVIO BOSCOLO (SB)",
        "Bairro": "Con. Habitacional Benedito José Diana",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "3 - ANDREIA",
        "CEP": "18542-386",
    },
    {
        "id": "24",
        "Rua": "SILVIO PELEGRINE - (SP) - 156-302",
        "Bairro": "Conjunto Habitacional Agostinho Alcalá",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "2",
        "CEP": "18542-364",
    },
    {
        "id": "25",
        "Rua": "SUZETE TOME ALCALA (STA)",
        "Bairro": "Jardim Excelsior",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "1 - FRANCIELLE",
        "CEP": "18542-322",
    },
    {
        "id": "26",
        "Rua": "VALTER ALBIEIRO (VA)",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "4 - GUILHERME",
        "CEP": "18542-372",
    },
    {
        "id": "27",
        "Rua": "WALTER CASTELUCCI (WC)",
        "Bairro": "Conj. Habitacional Benedito José Diana",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "1 - FRANCIELLE",
        "CEP": "18542-382",
    },
    {
        "id": "28",
        "Rua": "AGEU AUGUSTO DA SILVA (AAS)",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-308",
    },
    {
        "id": "29",
        "Rua": "ALZIRA PREVITALI (AP)",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-318",
    },
    {
        "id": "30",
        "Rua": "ANGELO GASTARDELLO (AG)",
        "Bairro": "Rua Ângelo Gastardello",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-358",
    },
    {
        "id": "31",
        "Rua": "ANGELO GIOVANI MENEGON (AGM)",
        "Bairro": "Jardim Martelli",
        "Medico": "AMARELA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-350",
    },
    {
        "id": "32",
        "Rua": "ANTONIO GIBIM (AG)",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "6 - JÉSSICA",
        "CEP": "18542-276",
    },
    {
        "id": "33",
        "Rua": "ARMANDO SALES DE OLIVEIRA (ASO) - 653 A 1070",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "6 - JÉSSICA",
        "CEP": "18542-260",
    },
    {
        "id": "34",
        "Rua": "AGOSTINHO ZARDETO (AZ)",
        "Bairro": "Jardim Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-354",
    },
    {
        "id": "35",
        "Rua": "AURORA MACHADO GUIMARAES (AMG)",
        "Bairro": "Conjunto Habitacional Agostinho Alcalá",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-362",
    },
    {
        "id": "36",
        "Rua": "AVELINO ALVES DE OLIVEIRA (AAO)",
        "Bairro": "Jardim Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-352",
    },
    {
        "id": "37",
        "Rua": "BENEDITA DE ALMEIDA LEAL (BAL)",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-314",
    },
    {
        "id": "38",
        "Rua": "DARIO MARTELI (DM)",
        "Bairro": "Residencial Humberto Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-226",
    },
    {
        "id": "39",
        "Rua": "FELICIO CASTELUCCI (FC) - 131 EM DIANTE",
        "Bairro": "Vila Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-244",
    },
    {
        "id": "40",
        "Rua": "GESSIA ODETE MORAES LISBOA (GOML) - 35 A 250",
        "Bairro": "Residencial Humberto Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-220",
    },
    {
        "id": "41",
        "Rua": "HUMBERTO MARTELLI (HM) - 134 EM DIANTE",
        "Bairro": "Residencial Humberto Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-232",
    },
    {
        "id": "42",
        "Rua": "ITAMAR SEGUNDO ALVES DE SANTANA (ISAS) - 29 A 181",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "1 - CLEISE",
        "CEP": "18542-312",
    },
    {
        "id": "43",
        "Rua": "JOAO DIANA SOBRINHO (JDS) - 15 A 257",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-324",
    },
    {
        "id": "44",
        "Rua": "JOAO MARINONIO DE CAMARGO (JMC) - 157 EM DIANTE",
        "Bairro": "Jardim Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-348",
    },
    {
        "id": "45",
        "Rua": "JOAO VICENTE FERREIRA (JVF)",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "6 - JÉSSICA",
        "CEP": "18542-278",
    },
    {
        "id": "46",
        "Rua": "JOSE CAETANO JESUS (JCJ) - 13, 17, 39",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "1 - CLEISE",
        "CEP": "18542-306",
    },
    {
        "id": "47",
        "Rua": "JOSE MARTINS TELES (JMT) - 05 A 835",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-300",
    },
    {
        "id": "48",
        "Rua": "JULIEN FOUQUE (JF) - 20 A 505",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "1 - CLEISE",
        "CEP": "18542-316",
    },
    {
        "id": "49",
        "Rua": "JULIO SOARES DIEL (JSD)",
        "Bairro": "Residencial Humberto Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-230",
    },
    {
        "id": "50",
        "Rua": "LAZARO DIAS SANTOS (LDS)",
        "Bairro": "Jardim Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-346",
    },
    {
        "id": "51",
        "Rua": "LUIZ CARLOS LISBOA (LCL) - 15 A 90",
        "Bairro": "Residencial Humberto Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-222",
    },
    {
        "id": "52",
        "Rua": "LUZIA DANIEL GHILBERT (LDG) - 47 A 77",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "1 - CLEISE",
        "CEP": "18542-302",
    },
    {
        "id": "53",
        "Rua": "MADRE SERAFINA (MS) - 164 A 420",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "5 - BRENA",
        "CEP": "18542-268",
    },
    {
        "id": "54",
        "Rua": "MARIA EUGENIA PIMENTA DIANA (MEPD) - 8-88",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-330",
    },
    {
        "id": "55",
        "Rua": "MARIA MARGARIDA PASCOAL (MMP)",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-310",
    },
    {
        "id": "56",
        "Rua": "MONSENHOR PIRES (MP) - 318 A 604",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "5 - BRENA",
        "CEP": "18542-272",
    },
    {
        "id": "57",
        "Rua": "OSVALDO NOVAES DE CARVALHO (ONC) - ATÉ 56",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-366",
    },
    {
        "id": "58",
        "Rua": "OTACILIO VALINI (OV)",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "",
        "CEP": "18542-280",
    },
    {
        "id": "59",
        "Rua": "OTONIEL MOTTA (OM) - 41 A 322",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "5 - BRENA",
        "CEP": "18542-274*",
    },
    {
        "id": "60",
        "Rua": "PADRE ALEXANDRE HOLDEAU (PAH) - 125 A 445",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "5 - BRENA",
        "CEP": "18542-270",
    },
    {
        "id": "61",
        "Rua": "RODOLFO MOTTA (RM)",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "6 - JÉSSICA",
        "CEP": "18542-266",
    },
    {
        "id": "62",
        "Rua": "ROSA GUARINI MARTELLI (RGM)",
        "Bairro": "Residencial Humberto Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-228",
    },
    {
        "id": "63",
        "Rua": "SAID NEIFE (SN)",
        "Bairro": "Jardim Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-342",
    },
    {
        "id": "64",
        "Rua": "SILVIA MARTELLI (SM)",
        "Bairro": "Residencial Humberto Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "4",
        "CEP": "18542-224",
    },
    {
        "id": "65",
        "Rua": "SILVIO PELEGRINE (SP) - 7 A 87",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "3",
        "CEP": "18542-364",
    },
    {
        "id": "66",
        "Rua": "SUZANA FRANCO ROCCO (SFR)",
        "Bairro": "",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "",
    },
    {
        "id": "67",
        "Rua": "VALDEREZ PIRES (VP) - 98, 102, 112, 115, 120, 171",
        "Bairro": "Jardim Excelsior",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "1 - CLEISE",
        "CEP": "18542-304",
    },
    {
        "id": "68",
        "Rua": "VILMA MARIA BOSCOLO (VMB)",
        "Bairro": "Conj. Habitacional Eugênio Motta",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-450",
    },
    {
        "id": "69",
        "Rua": "VIRGILINO DE OLIVEIRA SANTOS (VOS)",
        "Bairro": "Jardim Martelli",
        "Medico": "ANA PAULA",
        "Enfermeira": "Andrea",
        "Equipe": "AMARELA",
        "Micro": "2",
        "CEP": "18542-340",
    },
    {
        "id": "70",
        "Rua": "ADA CALGARO CAVALANTE (AGC)",
        "Bairro": "Jardim Rolando Giuli",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "1 - DAIANE",
        "CEP": "18542-520",
    },
    {
        "id": "71",
        "Rua": "ALZIRO CARLOS (AC)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18545-276",
    },
    {
        "id": "72",
        "Rua": "ANTONIO DARIO (AD)",
        "Bairro": "Belo Alto",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "5",
        "CEP": "18545-132",
    },
    {
        "id": "73",
        "Rua": "BENEDITO PRESTES SOUZA (BPS)",
        "Bairro": "Jardim Rolando Giuli",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "1 - DAIANE",
        "CEP": "18542-514",
    },
    {
        "id": "74",
        "Rua": "DOUTOR CELIO PRADO (DCP)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18545-278",
    },
    {
        "id": "75",
        "Rua": "CLARICE SANNA SERRALHEIRO (CSS)",
        "Bairro": "Conj. Habitacional Residencial Bello",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "4 - JULIA",
        "CEP": "18545-156",
    },
    {
        "id": "76",
        "Rua": "CLEITON BAZZO CUCHERA (CBC)",
        "Bairro": "Jardim Santa Terezinha",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-244",
    },
    {
        "id": "77",
        "Rua": "DANIEL DE CAMARGO TABORDA (DCT) - 485 EM DIANTE",
        "Bairro": "Parque Residencial Água Branca",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18542-470",
    },
    {
        "id": "78",
        "Rua": "DANIEL DA SILVA BRAGA (DSB)",
        "Bairro": "Jardim Esplanada",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18542-492",
    },
    {
        "id": "79",
        "Rua": "DANTE CAREZIA (DC)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18545-288",
    },
    {
        "id": "80",
        "Rua": "EDGAR MORAES (EM)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "5",
        "CEP": "18545-266",
    },
    {
        "id": "81",
        "Rua": "FELIPE MANOEL DE CAMPOS (FMC)",
        "Bairro": "-Parque Residencial Água Branca",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "3",
        "CEP": "18542-476",
    },
    {
        "id": "82",
        "Rua": "FLAVIA SAMPAIO BELLO (FSB)",
        "Bairro": "Belo Alto",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "5",
        "CEP": "18545-136",
    },
    {
        "id": "83",
        "Rua": "FRANCISCO MIGUEL MACEDO (FMM)",
        "Bairro": "Jardim Esplanada",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "1 - DAIANE",
        "CEP": "18542-494",
    },
    {
        "id": "84",
        "Rua": "IRENE SEGATO (IS)",
        "Bairro": "Jardim Santa Terezinha",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-242",
    },
    {
        "id": "85",
        "Rua": "JOAO BRASILIO DA SILVA (JBS)",
        "Bairro": "Conj. Habitacional Residencial Bello",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "4 - JULIA",
        "CEP": "18545-150",
    },
    {
        "id": "86",
        "Rua": "JOAO GASTARDELI (JG)",
        "Bairro": "Jardim Esplanada",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "2 - RENATA",
        "CEP": "18542-498",
    },
    {
        "id": "87",
        "Rua": "JOSE BARBOSA (JB)",
        "Bairro": "Jardim Rolando Giuli",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "1 - DAIANE",
        "CEP": "18542-516",
    },
    {
        "id": "88",
        "Rua": "JOSE MARTINS TELES (JMT) - 1135 A 1143",
        "Bairro": "Parque Residencial Água Branca",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-282",
    },
    {
        "id": "89",
        "Rua": "JOSE ROBERTO BATISTELA (JRB)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18545-272",
    },
    {
        "id": "90",
        "Rua": "LAURO GALVAO (LG)",
        "Bairro": "Parque Residencial Água Branca",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "2 - RENATA",
        "CEP": "18542-484",
    },
    {
        "id": "91",
        "Rua": "LAURA STEINER DE CARVALHO (LSC)",
        "Bairro": "Conj. Habitacional Residencial Bello",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "4 - JULIA",
        "CEP": "18545-154",
    },
    {
        "id": "92",
        "Rua": "LUIS TEMPESTA (LT)",
        "Bairro": "Jardim Esplanada",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "2 - RENATA",
        "CEP": "18542-496",
    },
    {
        "id": "93",
        "Rua": "MARIO CAMILO FILHO (MCF)",
        "Bairro": "Jardim Rolando Giu",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "1 - DAIANE",
        "CEP": "18542-518",
    },
    {
        "id": "94",
        "Rua": "MARIO COVAS (MC) - 1985 A 2945",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "5",
        "CEP": "18545-280",
    },
    {
        "id": "95",
        "Rua": "NORBERTO COELHO DE OLIVEIRA (NCO)",
        "Bairro": "Belo Alto",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "5",
        "CEP": "18545-134",
    },
    {
        "id": "96",
        "Rua": "OCIREMA FERNANDES STETNER (OFS)",
        "Bairro": "Belo Alto",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "5",
        "CEP": "18545-138",
    },
    {
        "id": "97",
        "Rua": "OLGA BRUGNEROTTO SGARIBOLDI (OBS)",
        "Bairro": "Jardim Santa Terezinha",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-248",
    },
    {
        "id": "98",
        "Rua": "PAULO DE OLIVEIRA TAUHYL (POT)",
        "Bairro": "Jardim Rolando Giuli",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "2 - RENATA",
        "CEP": "18542-500",
    },
    {
        "id": "99",
        "Rua": "PEDRO SGARIBOLDI (PS)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-284",
    },
    {
        "id": "100",
        "Rua": "PLINIO MARTINS TELES (PMT)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "4 - JULIA",
        "CEP": "18545-264",
    },
    {
        "id": "101",
        "Rua": "ROBERVAL CAMARGO DE MORAES (RCM)",
        "Bairro": "Jardim Rolando Giuli",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "1 - DAIANE",
        "CEP": "18542-508",
    },
    {
        "id": "102",
        "Rua": "ROMEU CASTELUCCI (RC)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18545-270",
    },
    {
        "id": "103",
        "Rua": "SANTA LUCIA MAGOGA (SLM)",
        "Bairro": "Jardim Santa Terezinha",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-236",
    },
    {
        "id": "104",
        "Rua": "SANTO SGARIBOLDI (SS)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18545-260",
    },
    {
        "id": "105",
        "Rua": "REVERENDO SILES BACARO (SB)",
        "Bairro": "Jardim Santa Terezinha",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-238",
    },
    {
        "id": "106",
        "Rua": "ULISSES ALVES MACHADO (UAM)",
        "Bairro": "Conj. Habitacional Residencial Bello",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "4 - JULIA",
        "CEP": "18545-152",
    },
    {
        "id": "107",
        "Rua": "VALDEMAR VERONEZE (VV)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "6",
        "CEP": "18545-268",
    },
    {
        "id": "108",
        "Rua": "VERGINIO ANGELIERE (VA)",
        "Bairro": "Parque Residencial Água Branca",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "2 - RENATA",
        "CEP": "18542-478",
    },
    {
        "id": "109",
        "Rua": "ADOLFO FERRARI (AF)",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "",
        "CEP": "18542-262",
    },
    {
        "id": "110",
        "Rua": "AMADEU MARTELLI (AM)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "3",
        "CEP": "18542-076",
    },
    {
        "id": "111",
        "Rua": "ANTONIO BELLO (AB)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-096",
    },
    {
        "id": "112",
        "Rua": "ANTONIO LEITE ALMEIDA (ALA)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "6 - TATIANE",
        "CEP": "18542-058",
    },
    {
        "id": "113",
        "Rua": "ARMANDO RAMOS (AR) - 38 a 214",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "6 - TATIANE",
        "CEP": "18542-060",
    },
    {
        "id": "114",
        "Rua": "ARMANDO SALES DE OLIVEIRA (ASO) - 174-585",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-074",
    },
    {
        "id": "115",
        "Rua": "ARMANDO SALES DE OLIVEIRA (ASO) - 12-169",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "6 - TATIANE",
        "CEP": "18542-074",
    },
    {
        "id": "116",
        "Rua": "ATILIO COLI (AC)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "3",
        "CEP": "18542-068",
    },
    {
        "id": "117",
        "Rua": "BENEDITO PIRES DE ARRUDA (BPA)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-072",
    },
    {
        "id": "118",
        "Rua": "BENEDITO DE TOLEDO VIEGAS / VIEIRA (BTV)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-106",
    },
    {
        "id": "119",
        "Rua": "BENEDITO VAZ CARDOSO (BVC)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-070",
    },
    {
        "id": "120",
        "Rua": "BOITUVA",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-156",
    },
    {
        "id": "121",
        "Rua": "CABREUVA",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-158",
    },
    {
        "id": "122",
        "Rua": "CANTIDIO / CANDIDO DE OLIVEIRA (CO)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-064",
    },
    {
        "id": "123",
        "Rua": "CERQUILHO",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "3",
        "CEP": "18542-164",
    },
    {
        "id": "124",
        "Rua": "EVARISTO BAPTISTELLA (EB)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-100",
    },
    {
        "id": "125",
        "Rua": "FELICIO CASTELUCCI (FC) - ATÉ 130",
        "Bairro": "Vila Martelli",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-244",
    },
    {
        "id": "126",
        "Rua": "GENESIO RODRIGUES (GR)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "6 - TATIANE",
        "CEP": "18542-056",
    },
    {
        "id": "127",
        "Rua": "HUMBERTO MARTELLI (HM) - ATÉ 120",
        "Bairro": "Vila Martelli",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-240",
    },
    {
        "id": "128",
        "Rua": "INDAIATUBA",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "3",
        "CEP": "18542-166",
    },
    {
        "id": "129",
        "Rua": "ITU",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-172",
    },
    {
        "id": "130",
        "Rua": "JOAO BATISTA DE CAMPOS (JBC)",
        "Bairro": "Jardim Sofia",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-182",
    },
    {
        "id": "131",
        "Rua": "JOAO MARINONIO DE CAMARGO (JMC) - ATÉ 140",
        "Bairro": "Vila Martelli",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-242",
    },
    {
        "id": "132",
        "Rua": "JOAO RODRIGUES DA SILVA (JRS)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18542-062",
    },
    {
        "id": "134",
        "Rua": "JOAQUIM PIRES ALMEIDA (JPA)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-066",
    },
    {
        "id": "135",
        "Rua": "JOSE GUERINI (JG)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-098",
    },
    {
        "id": "136",
        "Rua": "JOSE MARCELINO ANTUNES (JMA)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-102",
    },
    {
        "id": "137",
        "Rua": "JOSE TEIXEIRA DA FONSECA (JTF)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "3",
        "CEP": "18542-078",
    },
    {
        "id": "138",
        "Rua": "LUIZ ANTONIO VIEIRA (LAV)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-110",
    },
    {
        "id": "139",
        "Rua": "LUIS CARLOS RINCK (LCR)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-108",
    },
    {
        "id": "140",
        "Rua": "LUIZ MARTELI (LM)",
        "Bairro": "Vila Martelli",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "3",
        "CEP": "18542-254",
    },
    {
        "id": "141",
        "Rua": "MADRE SERAFINA (MS) - ATÉ 163",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-268",
    },
    {
        "id": "142",
        "Rua": "MARIA MARGARIDA COSSONICHE (MMC)",
        "Bairro": "Jardim Soﬁa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-184",
    },
    {
        "id": "143",
        "Rua": "MONSENHOR PIRES (MP) - ATÉ 286",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-272",
    },
    {
        "id": "144",
        "Rua": "NATALIO TAUHYL (NT)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-104",
    },
    {
        "id": "145",
        "Rua": "OLAVO ASSUMPÇAO FLEURY (OAF) - ATÉ 96",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "6 - TATIANE",
        "CEP": "18542-050",
    },
    {
        "id": "146",
        "Rua": "PADRE ALEXANDRE HORDEAU (PAH) - ATÉ 39",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-270",
    },
    {
        "id": "147",
        "Rua": "PASCOA BONINI GUERINI (PBG)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-092",
    },
    {
        "id": "148",
        "Rua": "PEDRO PAULO DE OLIVEIRA (PPO)",
        "Bairro": "Jardim Santa Eliza",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "5 - KAREN",
        "CEP": "18542-264*",
    },
    {
        "id": "149",
        "Rua": "PIRAPORA",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-160",
    },
    {
        "id": "150",
        "Rua": "ROQUE PLINIO DE CARVALHO (RPC)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "6 - TATIANE ",
        "CEP": "18542-052",
    },
    {
        "id": "151",
        "Rua": "SALTO",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "3",
        "CEP": "18542-162",
    },
    {
        "id": "152",
        "Rua": "SANTA ROSA (SR)",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-150",
    },
    {
        "id": "153",
        "Rua": "SOROCABA",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-168",
    },
    {
        "id": "154",
        "Rua": "TATUI",
        "Bairro": "Jardim Soﬁa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-180**",
    },
    {
        "id": "155",
        "Rua": "TIETE",
        "Bairro": "Jardim Santa Rosa",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "4 - MIRO",
        "CEP": "18542-170",
    },
    {
        "id": "156",
        "Rua": "ULISSES CORNELIO VITORINO (UCV)",
        "Bairro": "Vila Progresso",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "6 - TATIANE",
        "CEP": "18542-054",
    },
    {
        "id": "157",
        "Rua": "VITORIO BELO (VB)",
        "Bairro": "Residencial Bepim",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-094",
    },
    {
        "id": "158",
        "Rua": "GENESIO AZOLINE (GA)",
        "Bairro": "Residencial Portal Ville Ipê",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "2",
        "CEP": "18545-124",
    },
    {
        "id": "159",
        "Rua": "ALFREDO SALEM (AS)",
        "Bairro": "Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "4",
        "CEP": "18545-262",
    },
    {
        "id": "160",
        "Rua": "VICTORIO MARTELETTO (VM)",
        "Bairro": "Jardim Santa Terezinha",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-234",
    },
    {
        "id": "161",
        "Rua": "MARIA DE LOURDES RIBEIRO DA SILVA SERAFIM (MLRSS)",
        "Bairro": "Parque Residencial São Marcos",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-274",
    },
    {
        "id": "162",
        "Rua": "JOSE OLIVEIRA DE SOUZA (JOS)",
        "Bairro": "Jardim Santa Terezinha",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-240",
    },
    {
        "id": "165",
        "Rua": "PERES VENTURA (PV)",
        "Bairro": "Conj. Habitacional Agostinho Alcalá",
        "Medico": "PEDRO",
        "Enfermeira": "Julia",
        "Equipe": "PRATA",
        "Micro": "4 - GUILHERME",
        "CEP": "18542-368",
    },
    {
        "id": "166",
        "Rua": "TANCREDO DE ALMEIDA NEVES (TAN)",
        "Bairro": "Belo Alto",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "",
    },
    {
    "id": "167",
        "Rua": "LUIZ CARLOS LISBOA (LCL) - 91 EM DIANTE",
        "Bairro": "Residencial Portal Ville Ipê",
        "Medico": "BRUNO",
        "Enfermeira": "Milene",
        "Equipe": "OURO",
        "Micro": "",
        "CEP": "18545-120",
    },
    
    {
    "id": "168",
        "Rua": "AMELIO BARNABE (AB)",
        "Bairro": "Rolando Giuli",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18542-522",
    },

     {
    "id": "169",
        "Rua": "CARDOSO PIMENTEL (CP)",
        "Bairro": "Belo Alto",
        "Medico": "RENAN",
        "Enfermeira": "Maria Ap Maciel",
        "Equipe": "ROSA",
        "Micro": "",
        "CEP": "18545-130",
    },
];

state.data = data;
state.customData = data;
var tbody = document.getElementById("tbody");
state.valueSatus = "";
state.valueMedico = "";
state.numberDisplay = 0;
var tbody = document.getElementById("tbody");


// // for (let key in data) {
// //     // console.log(data[key],key,);
// //     let elem = create_elment(data[key]);
// //     tbody.insertAdjacentHTML('beforeend',elem);

// // }

function getEquipe(self) {
    switch (self) {
        case 'PRATA':
            return 'class="Equipe prata"';
            break;
        case 'OURO':
            return 'class="Equipe ouro"';
            break;
        case 'AMARELA':
            return 'class="Equipe amarela"';
            break;
        case 'ROSA':
            return 'class="Equipe rosa"';
            break;
        default:
            return 'class="Equipe text-success"';
            break;
    }
}

function create_elment(item) {
    return `
    <tr>
        <td>${item.Rua}</td>
        <td>${item.Bairro.toUpperCase()}</td>
        <td><span `+ getEquipe(item.Equipe) + `>•</span> ${item.Equipe}</td>
        <td>${item.Medico}</td>
        <td>${item.Enfermeira}</td>                        
        <td>${item.Micro}</td>
        <td>${item.CEP}</td>
    </tr>
    `;
}


loadData();

// console.log(get_text);
//ds

var numberBD = document.getElementById('number1').innerHTML;
var numberKT = document.getElementById('number2').innerHTML;

function loadData() {
    document.getElementById('number1').innerHTML = 1;
    document.getElementById('number2').innerHTML = 5;
    state.valueEntries = 5;
    state.valueEquipe = "Any";
    state.valueMedico = "All";
    let data = state.customData.slice(0, 0);
    tbody.innerHTML = "";
    data.forEach(item => {
        tbody.insertAdjacentHTML('beforeend', create_elment(item));
    })
}


var select = document.getElementById("select-entries");
var num_entries;
var numPage;
var show;

var dem;

//tao li
function create_li(item) {
    return `
        <a onclick="changeclick(this)" href="#" class="page-link">${item}</a>
    `;
}
function changeclick(id) {
    return 1;
}

taosubpag();
ktshow();
chia_theo_show();
function taosubpag() {
    var subpage = document.getElementById("subpage");
    for (var i = 1; i <= Math.ceil(data.length / 5); i++) {
        var li = document.createElement("li");
        li.innerHTML = create_li(i);
        subpage.appendChild(li);
    }
};

function ktshow() {
    document.getElementById('select-entries').addEventListener('change', e => {
        let selectDataforEntry = state.customData.slice(0, e.target.value);
        tbody.innerHTML = "";
        selectDataforEntry.forEach(item => {
            tbody.insertAdjacentHTML('beforeend', create_elment(item));
        })
    });


}
var select = document.getElementById("select-entries");
var num_entries;
var numPage;
function chia_theo_show() {

    select.onchange = function () {
        var option = select.children;
        for (var i = 0; i < option.length; i++) {
            if (option[i].selected) {
                num_entries = option[i].value;
            }
        }
        numPage = Math.ceil(data.length / num_entries);
        document.getElementById('number1').innerHTML = 1;
        document.getElementById('number2').innerHTML = num_entries;
        subpage.innerHTML = "";
        for (var i = 1; i <= numPage; i++) {
            var li = document.createElement("li");
            li.innerHTML = create_li(i);
            li.value = i;
            subpage.appendChild(li);
        }
    }
}


var luaChon = subpage.children;
var page = document.getElementById("page");
var so;
    for (var i = 1; i <= luaChon.length; i++) {
        if (changeclick(luaChon[i])==1)
            so=i;
    }


    var search = document.getElementById("search");
search.addEventListener("keyup", function () {
    var searchValue = (document.getElementById("search").value).toLowerCase();
    tbody.innerHTML = "";
    if (searchValue == "")
        load();
    else {
        for (var i = 0; i < data.length; i++) {
            if (searchValue != "") {
                if (data[i].id.indexOf(searchValue) >= 0 || (data[i].Rua).toLowerCase().indexOf(searchValue) >= 0 || (data[i].Bairro).toLowerCase().indexOf(searchValue) >= 0 || (data[i].Equipe).toLowerCase().indexOf(searchValue) >= 0)
                    xuat(data[i]);
            }

        }
    }
});

function xuat(item) {

    var tr = document.createElement("tr");
    tr.innerHTML = create_elment(item);
    tbody.appendChild(tr);
}

function load() {
    /*for (var i = 0; i < 0; i++) {
        //console.log(data[i]);
        //console.log(item);
        var tr = document.createElement("tr");
        tr.innerHTML = create_elment(data[i]);
        tbody.appendChild(tr);
    }*/
}
